import type { INodeProperties } from 'n8n-workflow';

export const itAutomationOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['itAutomation'],
			},
		},
		options: [
			{ name: 'Cancel Task Execution', value: 'iTAutomationCancelTaskExecution', description: 'Cancel a task execution specified in the request', action: 'Cancel task execution' },
			{ name: 'Combined Scheduled Tasks', value: 'iTAutomationCombinedScheduledTasks', description: 'Returns full details of scheduled tasks matching filter', action: 'Combined scheduled tasks' },
			{ name: 'Create Policy', value: 'iTAutomationCreatePolicy', description: 'Creates a new policy of the specified type', action: 'Create policy' },
			{ name: 'Create Scheduled Task', value: 'iTAutomationCreateScheduledTask', description: 'Creates a scheduled task from the given request', action: 'Create scheduled task' },
			{ name: 'Create Task', value: 'iTAutomationCreateTask', description: 'Creates a task with details from the given request', action: 'Create task' },
			{ name: 'Create Task Group', value: 'iTAutomationCreateTaskGroup', description: 'Creates a task group from the given request', action: 'Create task group' },
			{ name: 'Create User Group', value: 'iTAutomationCreateUserGroup', description: 'Creates a user group from the given request', action: 'Create user group' },
			{ name: 'Delete Policy', value: 'iTAutomationDeletePolicy', description: 'Deletes 1 or more disabled policies', action: 'Delete policy' },
			{ name: 'Delete Scheduled Tasks', value: 'iTAutomationDeleteScheduledTasks', description: 'Delete one or more scheduled tasks by ID', action: 'Delete scheduled tasks' },
			{ name: 'Delete Task', value: 'iTAutomationDeleteTask', description: 'Deletes tasks for each provided ID', action: 'Delete task' },
			{ name: 'Delete Task Groups', value: 'iTAutomationDeleteTaskGroups', description: 'Delete one or more task groups by ID', action: 'Delete task groups' },
			{ name: 'Delete User Group', value: 'iTAutomationDeleteUserGroup', description: 'Deletes user groups for each provided ID', action: 'Delete user group' },
			{ name: 'Get Associated Tasks', value: 'iTAutomationGetAssociatedTasks', description: 'Retrieve tasks associated with the provided file ID', action: 'Get associated tasks' },
			{ name: 'Get Execution Results', value: 'iTAutomationGetExecutionResults', description: 'Get the task execution results from an async search', action: 'Get execution results' },
			{ name: 'Get Execution Results Search Status', value: 'iTAutomationGetExecutionResultsSearchStatus', description: 'Get the status of an async task execution results search', action: 'Get execution results search status' },
			{ name: 'Get Policies', value: 'iTAutomationGetPolicies', description: 'Retrieves the configuration for 1 or more policies', action: 'Get policies' },
			{ name: 'Get Scheduled Tasks', value: 'iTAutomationGetScheduledTasks', description: 'Returns scheduled tasks for each provided ID', action: 'Get scheduled tasks' },
			{ name: 'Get Task Execution', value: 'iTAutomationGetTaskExecution', description: 'Get the task execution for provided task execution IDs', action: 'Get task execution' },
			{ name: 'Get Task Execution Host Status', value: 'iTAutomationGetTaskExecutionHostStatus', description: 'Get the status of host executions by providing execution IDs', action: 'Get task execution host status' },
			{ name: 'Get Task Executions by Query', value: 'iTAutomationGetTaskExecutionsByQuery', description: 'Returns list of task executions matching filter query', action: 'Get task executions by query' },
			{ name: 'Get Task Groups', value: 'iTAutomationGetTaskGroups', description: 'Returns task groups for each provided ID', action: 'Get task groups' },
			{ name: 'Get Task Groups by Query', value: 'iTAutomationGetTaskGroupsByQuery', description: 'Returns full details of task groups matching filter', action: 'Get task groups by query' },
			{ name: 'Get Tasks', value: 'iTAutomationGetTasks', description: 'Returns tasks for each provided ID', action: 'Get tasks' },
			{ name: 'Get Tasks by Query', value: 'iTAutomationGetTasksByQuery', description: 'Returns full details of tasks matching filter', action: 'Get tasks by query' },
			{ name: 'Get User Group', value: 'iTAutomationGetUserGroup', description: 'Returns user groups for each provided ID', action: 'Get user group' },
			{ name: 'Query Policies', value: 'iTAutomationQueryPolicies', description: 'Returns list of policy IDs matching filter query', action: 'Query policies' },
			{ name: 'Rerun Task Execution', value: 'iTAutomationRerunTaskExecution', description: 'Rerun the task execution specified in the request', action: 'Rerun task execution' },
			{ name: 'Run Live Query', value: 'iTAutomationRunLiveQuery', description: 'Starts a new task execution from provided query data', action: 'Run live query' },
			{ name: 'Search Scheduled Tasks', value: 'iTAutomationSearchScheduledTasks', description: 'Returns list of scheduled task IDs matching filter', action: 'Search scheduled tasks' },
			{ name: 'Search Task Executions', value: 'iTAutomationSearchTaskExecutions', description: 'Returns list of task execution IDs matching filter', action: 'Search task executions' },
			{ name: 'Search Task Groups', value: 'iTAutomationSearchTaskGroups', description: 'Returns list of task group IDs matching filter', action: 'Search task groups' },
			{ name: 'Search Tasks', value: 'iTAutomationSearchTasks', description: 'Returns list of task IDs matching filter query', action: 'Search tasks' },
			{ name: 'Search User Group', value: 'iTAutomationSearchUserGroup', description: 'Returns list of user group IDs matching filter query', action: 'Search user group' },
			{ name: 'Start Execution Results Search', value: 'iTAutomationStartExecutionResultsSearch', description: 'Starts an async task execution results search', action: 'Start execution results search' },
			{ name: 'Start Task Execution', value: 'iTAutomationStartTaskExecution', description: 'Starts a new task execution from an existing task', action: 'Start task execution' },
			{ name: 'Update Policies', value: 'iTAutomationUpdatePolicies', description: 'Updates multiple fields for a policy', action: 'Update policies' },
			{ name: 'Update Policies Precedence', value: 'iTAutomationUpdatePoliciesPrecedence', description: 'Updates policy precedence for all policies of a specific platform', action: 'Update policies precedence' },
			{ name: 'Update Policy Host Groups', value: 'iTAutomationUpdatePolicyHostGroups', description: 'Manage host groups assigned to a policy', action: 'Update policy host groups' },
			{ name: 'Update Scheduled Task', value: 'iTAutomationUpdateScheduledTask', description: 'Update an existing scheduled task', action: 'Update scheduled task' },
			{ name: 'Update Task', value: 'iTAutomationUpdateTask', description: 'Update a task with details from given request', action: 'Update task' },
			{ name: 'Update Task Group', value: 'iTAutomationUpdateTaskGroup', description: 'Update a task group for a given ID', action: 'Update task group' },
			{ name: 'Update User Group', value: 'iTAutomationUpdateUserGroup', description: 'Update a user group for a given ID', action: 'Update user group' },
		],
		default: 'iTAutomationSearchTasks',
	},
];

export const itAutomationFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationGetAssociatedTasks',
					'iTAutomationGetExecutionResults',
					'iTAutomationGetExecutionResultsSearchStatus',
					'iTAutomationUpdateScheduledTask',
					'iTAutomationUpdateTask',
					'iTAutomationUpdateTaskGroup',
					'iTAutomationUpdateUserGroup',
				],
			},
		},
		default: '',
		required: true,
		description: 'Unique object or file ID',
	},
	{
		displayName: 'IDs',
		name: 'ids',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationDeletePolicy',
					'iTAutomationDeleteScheduledTasks',
					'iTAutomationDeleteTask',
					'iTAutomationDeleteTaskGroups',
					'iTAutomationDeleteUserGroup',
					'iTAutomationGetPolicies',
					'iTAutomationGetScheduledTasks',
					'iTAutomationGetTaskExecution',
					'iTAutomationGetTaskExecutionHostStatus',
					'iTAutomationGetTaskGroups',
					'iTAutomationGetTasks',
					'iTAutomationGetUserGroup',
				],
			},
		},
		default: '',
		required: true,
		description: 'Comma-separated list of IDs',
	},
	{
		displayName: 'Platform',
		name: 'platform',
		type: 'options',
		options: [
			{ name: 'Windows', value: 'Windows' },
			{ name: 'Mac', value: 'Mac' },
			{ name: 'Linux', value: 'Linux' },
		],
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: ['iTAutomationQueryPolicies', 'iTAutomationUpdatePoliciesPrecedence'],
			},
		},
		default: 'Windows',
		required: true,
		description: 'OS Platform',
	},
	{
		displayName: 'Body (JSON)',
		name: 'bodyJson',
		type: 'json',
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationCancelTaskExecution',
					'iTAutomationCreatePolicy',
					'iTAutomationCreateScheduledTask',
					'iTAutomationCreateTask',
					'iTAutomationCreateTaskGroup',
					'iTAutomationCreateUserGroup',
					'iTAutomationRerunTaskExecution',
					'iTAutomationRunLiveQuery',
					'iTAutomationStartExecutionResultsSearch',
					'iTAutomationStartTaskExecution',
					'iTAutomationUpdatePolicies',
					'iTAutomationUpdatePoliciesPrecedence',
					'iTAutomationUpdatePolicyHostGroups',
					'iTAutomationUpdateScheduledTask',
					'iTAutomationUpdateTask',
					'iTAutomationUpdateTaskGroup',
					'iTAutomationUpdateUserGroup',
				],
			},
		},
		default: '',
		required: true,
		description: 'JSON request payload',
	},
	{
		displayName: 'Filter',
		name: 'filter',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationCombinedScheduledTasks',
					'iTAutomationGetAssociatedTasks',
					'iTAutomationGetTaskExecutionHostStatus',
					'iTAutomationGetTaskExecutionsByQuery',
					'iTAutomationGetTaskGroupsByQuery',
					'iTAutomationGetTasksByQuery',
					'iTAutomationSearchScheduledTasks',
					'iTAutomationSearchTaskExecutions',
					'iTAutomationSearchTaskGroups',
					'iTAutomationSearchTasks',
					'iTAutomationSearchUserGroup',
				],
			},
		},
		default: '',
		description: 'FQL filter string',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
			maxValue: 500,
		},
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationCombinedScheduledTasks',
					'iTAutomationGetAssociatedTasks',
					'iTAutomationGetExecutionResults',
					'iTAutomationGetTaskExecutionHostStatus',
					'iTAutomationGetTaskExecutionsByQuery',
					'iTAutomationGetTaskGroupsByQuery',
					'iTAutomationGetTasksByQuery',
					'iTAutomationQueryPolicies',
					'iTAutomationSearchScheduledTasks',
					'iTAutomationSearchTaskExecutions',
					'iTAutomationSearchTaskGroups',
					'iTAutomationSearchTasks',
					'iTAutomationSearchUserGroup',
				],
			},
		},
		default: 100,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: {
			minValue: 0,
		},
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationCombinedScheduledTasks',
					'iTAutomationGetAssociatedTasks',
					'iTAutomationGetExecutionResults',
					'iTAutomationGetTaskExecutionHostStatus',
					'iTAutomationGetTaskExecutionsByQuery',
					'iTAutomationGetTaskGroupsByQuery',
					'iTAutomationGetTasksByQuery',
					'iTAutomationQueryPolicies',
					'iTAutomationSearchScheduledTasks',
					'iTAutomationSearchTaskExecutions',
					'iTAutomationSearchTaskGroups',
					'iTAutomationSearchTasks',
					'iTAutomationSearchUserGroup',
				],
			},
		},
		default: 0,
		description: 'Starting index for pagination',
	},
	{
		displayName: 'Sort',
		name: 'sort',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['itAutomation'],
				operation: [
					'iTAutomationCombinedScheduledTasks',
					'iTAutomationGetAssociatedTasks',
					'iTAutomationGetExecutionResults',
					'iTAutomationGetTaskExecutionHostStatus',
					'iTAutomationGetTaskExecutionsByQuery',
					'iTAutomationGetTaskGroupsByQuery',
					'iTAutomationGetTasksByQuery',
					'iTAutomationQueryPolicies',
					'iTAutomationSearchScheduledTasks',
					'iTAutomationSearchTaskExecutions',
					'iTAutomationSearchTaskGroups',
					'iTAutomationSearchTasks',
					'iTAutomationSearchUserGroup',
				],
			},
		},
		default: '',
		description: 'Sort criteria',
	},
];
