sonar.projectKey=n8n-node-falcon
sonar.projectName=N8N Node Falcon
sonar.projectVersion=1.0.0

sonar.sources=credentials,nodes

sonar.sourceEncoding=UTF-8
sonar.language=ts

sonar.exclusions=**/node_modules/**, **/dist/**, **/*.tgz, **/*.svg
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.types.ts, **/*.test.ts, **/*.spec.ts