import type { INodeProperties } from 'n8n-workflow';

import { createBodyJsonField, createIdsField, createOperationField, createStandardPaginationFields } from '../common';

export const kubernetesProtectionOperations: INodeProperties[] = [
	createOperationField('kubernetesProtection', [

			{ name: 'Cluster Combined', value: 'clusterCombined', description: 'Retrieve kubernetes clusters identified by filter criteria', action: 'Cluster combined' },
			{ name: 'Cluster Count', value: 'clusterCount', description: 'Retrieve cluster counts', action: 'Cluster count' },
			{ name: 'Cluster Enrichment', value: 'clusterEnrichment', description: 'Retrieve cluster enrichment data', action: 'Cluster enrichment' },
			{ name: 'Clusters by Date Range Count', value: 'clustersByDateRangeCount', description: 'Retrieve clusters by date range counts', action: 'Clusters by date range count' },
			{ name: 'Clusters by Kubernetes Version Count', value: 'clustersByKubernetesVersionCount', description: 'Bucket clusters by kubernetes version', action: 'Clusters by kubernetes version count' },
			{ name: 'Clusters by Status Count', value: 'clustersByStatusCount', description: 'Bucket clusters by status', action: 'Clusters by status count' },
			{ name: 'Container Combined', value: 'containerCombined', description: 'Retrieves a paginated list of containers identified by filter criteria', action: 'Container combined' },
			{ name: 'Container Count', value: 'containerCount', description: 'Retrieve container counts', action: 'Container count' },
			{ name: 'Container Count by Registry', value: 'containerCountByRegistry', description: 'Retrieves a list with the top container image registries', action: 'Container count by registry' },
			{ name: 'Container Enrichment', value: 'containerEnrichment', description: 'Retrieve container enrichment data', action: 'Container enrichment' },
			{ name: 'Container Image Detections Count by Date', value: 'containerImageDetectionsCountByDate', description: 'Retrieve count of image assessment detections on running containers', action: 'Container image detections count by date' },
			{ name: 'Container Images by Most Used', value: 'containerImagesByMostUsed', description: 'Bucket container by image-digest', action: 'Container images by most used' },
			{ name: 'Container Images by State', value: 'containerImagesByState', description: 'Retrieve count of image states running on containers', action: 'Container images by state' },
			{ name: 'Container Vulnerabilities by Severity Count', value: 'containerVulnerabilitiesBySeverityCount', description: 'Retrieve container vulnerabilities by severity counts', action: 'Container vulnerabilities by severity count' },
			{ name: 'Containers by Date Range Count', value: 'containersByDateRangeCount', description: 'Retrieve containers by date range counts', action: 'Containers by date range count' },
			{ name: 'Containers Sensor Coverage', value: 'containersSensorCoverage', description: 'Bucket containers by agent type and calculate sensor coverage', action: 'Containers sensor coverage' },
			{ name: 'Create AWS Account', value: 'createAWSAccount', description: 'Creates a new AWS account in system and generates installation script', action: 'Create AWS account' },
			{ name: 'Create Azure Subscription', value: 'createAzureSubscription', description: 'Creates a new Azure Subscription in system', action: 'Create Azure subscription' },
			{ name: 'Delete AWS Accounts', value: 'deleteAWSAccountsMixin0', description: 'Delete AWS accounts', action: 'Delete AWS accounts' },
			{ name: 'Delete Azure Subscription', value: 'deleteAzureSubscription', description: 'Deletes Azure Subscriptions in system', action: 'Delete Azure subscription' },
			{ name: 'Deployment Combined', value: 'deploymentCombined', description: 'Retrieve kubernetes deployments identified by filter criteria', action: 'Deployment combined' },
			{ name: 'Deployment Count', value: 'deploymentCount', description: 'Retrieve deployment counts', action: 'Deployment count' },
			{ name: 'Deployment Enrichment', value: 'deploymentEnrichment', description: 'Retrieve deployment enrichment data', action: 'Deployment enrichment' },
			{ name: 'Deployments by Date Range Count', value: 'deploymentsByDateRangeCount', description: 'Retrieve deployments by date range counts', action: 'Deployments by date range count' },
			{ name: 'Distinct Container Image Count', value: 'distinctContainerImageCount', description: 'Retrieve count of distinct images running on containers', action: 'Distinct container image count' },
			{ name: 'Find Containers by Container Runtime Version', value: 'findContainersByContainerRunTimeVersion', description: 'Retrieve containers by container_runtime_version', action: 'Find containers by container runtime version' },
			{ name: 'Find Containers Count Affected by Zero Day Vulnerabilities', value: 'findContainersCountAffectedByZeroDayVulnerabilities', description: 'Retrieve containers count affected by zero day vulnerabilities', action: 'Find containers count affected by zero day vulnerabilities' },
			{ name: 'Get AWS Accounts', value: 'getAWSAccountsMixin0', description: 'Provides a list of AWS accounts', action: 'Get AWS accounts' },
			{ name: 'Get Azure Install Script', value: 'getAzureInstallScript', description: 'Provides script to run for given tenant ID and subscription IDs', action: 'Get Azure install script' },
			{ name: 'Get Azure Tenant Config', value: 'getAzureTenantConfig', description: 'Gets the Azure tenant Config', action: 'Get Azure tenant config' },
			{ name: 'Get Azure Tenant IDs', value: 'getAzureTenantIDs', description: 'Provides all azure subscriptions and tenants', action: 'Get Azure tenant IDs' },
			{ name: 'Get Clusters', value: 'getClusters', description: 'Provides clusters acknowledged by Kubernetes Protection service', action: 'Get clusters' },
			{ name: 'Get Combined Cloud Clusters', value: 'getCombinedCloudClusters', description: 'Returns combined list of provisioned cloud accounts and clusters', action: 'Get combined cloud clusters' },
			{ name: 'Get Helm Values YAML', value: 'getHelmValuesYaml', description: 'Provides sample Helm values.yaml file for agent Helm chart', action: 'Get Helm values YAML' },
			{ name: 'Get Locations', value: 'getLocations', description: 'Provides cloud locations acknowledged by Kubernetes Protection', action: 'Get locations' },
			{ name: 'Get Static Scripts', value: 'getStaticScripts', description: 'Gets static bash scripts used during registration', action: 'Get static scripts' },
			{ name: 'Group Containers by Managed', value: 'groupContainersByManaged', description: 'Group the containers by Managed', action: 'Group containers by managed' },
			{ name: 'Kubernetes IOM by Date Range', value: 'kubernetesIomByDateRange', description: 'Returns count of Kubernetes IOMs by date range', action: 'Kubernetes IOM by date range' },
			{ name: 'Kubernetes IOM Count', value: 'kubernetesIomCount', description: 'Returns total count of Kubernetes IOMs', action: 'Kubernetes IOM count' },
			{ name: 'Kubernetes IOM Entities', value: 'kubernetesIomEntities', description: 'Retrieve Kubernetes IOM entities by IDs', action: 'Kubernetes IOM entities' },
			{ name: 'Kubernetes IOM Entities Combined', value: 'kubernetesIomEntitiesCombined', description: 'Retrieves list of Kubernetes IOMs by search criteria', action: 'Kubernetes IOM entities combined' },
			{ name: 'List Azure Accounts', value: 'listAzureAccounts', description: 'Provides azure subscriptions registered to Kubernetes Protection', action: 'List Azure accounts' },
			{ name: 'Node Combined', value: 'nodeCombined', description: 'Retrieve kubernetes nodes identified by filter criteria', action: 'Node combined' },
			{ name: 'Node Count', value: 'nodeCount', description: 'Retrieve node counts', action: 'Node count' },
			{ name: 'Node Enrichment', value: 'nodeEnrichment', description: 'Retrieve node enrichment data', action: 'Node enrichment' },
			{ name: 'Nodes by Cloud Count', value: 'nodesByCloudCount', description: 'Bucket nodes by cloud providers', action: 'Nodes by cloud count' },
			{ name: 'Nodes by Container Engine Version Count', value: 'nodesByContainerEngineVersionCount', description: 'Bucket nodes by container engine version', action: 'Nodes by container engine version count' },
			{ name: 'Nodes by Date Range Count', value: 'nodesByDateRangeCount', description: 'Retrieve nodes by date range counts', action: 'Nodes by date range count' },
			{ name: 'Patch Azure Service Principal', value: 'patchAzureServicePrincipal', description: 'Adds client ID for given tenant ID to system', action: 'Patch Azure service principal' },
			{ name: 'Pod Combined', value: 'podCombined', description: 'Retrieve kubernetes pods identified by filter criteria', action: 'Pod combined' },
			{ name: 'Pod Count', value: 'podCount', description: 'Retrieve pod counts', action: 'Pod count' },
			{ name: 'Pod Enrichment', value: 'podEnrichment', description: 'Retrieve pod enrichment data', action: 'Pod enrichment' },
			{ name: 'Pods by Date Range Count', value: 'podsByDateRangeCount', description: 'Retrieve pods by date range counts', action: 'Pods by date range count' },
			{ name: 'Post Aggregates Pods', value: 'postAggregatesPods', description: 'Get aggregate query result for pods', action: 'Post aggregates pods' },
			{ name: 'Post Search Kubernetes IOM Entities', value: 'postSearchKubernetesIOMEntities', description: 'Search for Kubernetes IOMs with filtering options', action: 'Post search Kubernetes IOM entities' },
			{ name: 'Query Kubernetes IOMs', value: 'queryKubernetesIoms', description: 'Search Kubernetes IOMs returning list of UUIDs', action: 'Query Kubernetes IOMs' },
			{ name: 'Read Cluster Combined V2', value: 'readClusterCombinedV2', description: 'Retrieve Kubernetes cluster data V2', action: 'Read cluster combined V2' },
			{ name: 'Read Namespace Count', value: 'readNamespaceCount', description: 'Retrieve namespace counts', action: 'Read namespace count' },
			{ name: 'Read Namespaces by Date Range Count', value: 'readNamespacesByDateRangeCount', description: 'Retrieve namespaces by date range counts', action: 'Read namespaces by date range count' },
			{ name: 'Regenerate API Key', value: 'regenerateAPIKey', description: 'Regenerate API key for docker registry integrations', action: 'Regenerate API key' },
			{ name: 'Running Container Images', value: 'runningContainerImages', description: 'Retrieve images on running containers', action: 'Running container images' },
			{ name: 'Trigger Scan', value: 'triggerScan', description: 'Triggers dry run or full scan of kubernetes footprint', action: 'Trigger scan' },
			{ name: 'Update AWS Account', value: 'updateAWSAccount', description: 'Updates AWS account per query parameters', action: 'Update AWS account' },
			{ name: 'Vulnerable Container Image Count', value: 'vulnerableContainerImageCount', description: 'Retrieve count of vulnerable images running on containers', action: 'Vulnerable container image count' },
		
	], 'getClusters'),
];

export const kubernetesProtectionFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['kubernetesProtection'],
				operation: ['getAzureInstallScript', 'patchAzureServicePrincipal'],
			},
		},
		default: '',
		description: 'Unique ID string',
	},
	{
		displayName: 'Client ID',
		name: 'clientId',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['kubernetesProtection'],
				operation: ['patchAzureServicePrincipal'],
			},
		},
		default: '',
		required: true,
		description: 'Client ID string',
	},
	{
		displayName: 'Cluster Name',
		name: 'clusterName',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['kubernetesProtection'],
				operation: ['getHelmValuesYaml'],
			},
		},
		default: '',
		required: true,
		description: 'Name of the cluster',
	},
	createIdsField('kubernetesProtection', ['clusterEnrichment',
					'containerEnrichment',
					'deleteAWSAccountsMixin0',
					'deleteAzureSubscription',
					'deploymentEnrichment',
					'getAWSAccountsMixin0',
					'getAzureTenantConfig',
					'getAzureTenantIDs',
					'getCombinedCloudClusters',
					'kubernetesIomEntities',
					'listAzureAccounts',
					'nodeEnrichment',
					'podEnrichment',
					'updateAWSAccount',]),
	{
		displayName: 'Scan Type',
		name: 'scanType',
		type: 'options',
		options: [
			{ name: 'Cluster Refresh', value: 'cluster-refresh' },
			{ name: 'Dry Run', value: 'dry-run' },
			{ name: 'Full', value: 'full' },
		],
		displayOptions: {
			show: {
				resource: ['kubernetesProtection'],
				operation: ['triggerScan'],
			},
		},
		default: 'full',
		required: true,
		description: 'Type of scan to trigger',
	},
	{
		displayName: 'Region',
		name: 'region',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['kubernetesProtection'],
				operation: ['updateAWSAccount'],
			},
		},
		default: '',
		description: 'AWS Region',
	},
	createBodyJsonField('kubernetesProtection', ['createAWSAccount',
					'createAzureSubscription',
					'postAggregatesPods',
					'postSearchKubernetesIOMEntities',]),
	...createStandardPaginationFields('kubernetesProtection', ['clusterCombined',
					'clusterCount',
					'clustersByKubernetesVersionCount',
					'clustersByStatusCount',
					'containerCombined',
					'containerCount',
					'containerCountByRegistry',
					'containerImageDetectionsCountByDate',
					'containerImagesByMostUsed',
					'containerImagesByState',
					'containerVulnerabilitiesBySeverityCount',
					'containersByDateRangeCount',
					'containersSensorCoverage',
					'deploymentCombined',
					'deploymentCount',
					'distinctContainerImageCount',
					'findContainersByContainerRunTimeVersion',
					'groupContainersByManaged',
					'kubernetesIomByDateRange',
					'kubernetesIomCount',
					'kubernetesIomEntitiesCombined',
					'nodeCombined',
					'nodeCount',
					'nodesByCloudCount',
					'nodesByContainerEngineVersionCount',
					'nodesByDateRangeCount',
					'podCombined',
					'podCount',
					'postSearchKubernetesIOMEntities',
					'queryKubernetesIoms',
					'readClusterCombinedV2',
					'readNamespaceCount',
					'runningContainerImages',
					'vulnerableContainerImageCount',]),
];
