import type { INodeProperties } from 'n8n-workflow';

export const defaultOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['default'],
			},
		},
		options: [
			{ name: 'Combined Query Installed Patches', value: 'combinedQueryInstalledPatches', description: 'Get installed patches information for hosts', action: 'Combined query installed patches' },
			{ name: 'Delete Collections V1', value: 'deleteCollectionsV1', description: 'Cancel Collections', action: 'Delete collections v1' },
			{ name: 'Delete Configs V1', value: 'deleteConfigsV1', description: 'Retires a custom configuration', action: 'Delete configs v1' },
			{ name: 'Falcon Complete Dashboards Queries Detects V1', value: 'falconCompleteDashboardsQueriesDetectsV1Get', description: 'Query detects for Falcon Complete dashboards', action: 'Falcon complete dashboards queries detects v1' },
			{ name: 'Falcon Complete Dashboards Queries Incidents V1', value: 'falconCompleteDashboardsQueriesIncidentsV1Get', description: 'Query incidents for Falcon Complete dashboards', action: 'Falcon complete dashboards queries incidents v1' },
			{ name: 'Get Collection Counts by V1', value: 'getCollectionCountsByV1', description: 'Get Collection counts by field names', action: 'Get collection counts by v1' },
			{ name: 'Get Collections V1', value: 'getCollectionsV1', description: 'Get Collections with given IDs, Platform, Agent/Collector IDs, States', action: 'Get collections v1' },
			{ name: 'Get Collectors V1', value: 'getCollectorsV1', description: 'Get collectors', action: 'Get collectors v1' },
			{ name: 'Get Combined Collections V1', value: 'getCombinedCollectionsV1', description: 'Get Combined Collections for Customer ID', action: 'Get combined collections v1' },
			{ name: 'Get Combined Collectors V1', value: 'getCombinedCollectorsV1', description: 'Get collectors for the given Customer ID', action: 'Get combined collectors v1' },
			{ name: 'Get Combined Configs V1', value: 'getCombinedConfigsV1', description: 'Get Configurations for the given Customer ID', action: 'Get combined configs v1' },
			{ name: 'Get Combined Templates V1', value: 'getCombinedTemplatesV1', description: 'Get Templates with the given IDs', action: 'Get combined templates v1' },
			{ name: 'Get Config Download V1', value: 'getConfigDownloadV1', description: 'Download offline Configuration file using ID', action: 'Get config download v1' },
			{ name: 'Get Configs V1', value: 'getConfigsV1', description: 'Get Configurations with the given IDs', action: 'Get configs v1' },
			{ name: 'Get Templates V1', value: 'getTemplatesV1', description: 'Get Templates with the given IDs', action: 'Get templates v1' },
			{ name: 'Post Collections V1', value: 'postCollectionsV1', description: 'Create Collections', action: 'Post collections v1' },
			{ name: 'Post Collectors V1', value: 'postCollectorsV1', description: 'Shutdown collectors with self_destruct option', action: 'Post collectors v1' },
			{ name: 'Post Configs V1', value: 'postConfigsV1', description: 'Creates a new custom configuration', action: 'Post configs v1' },
			{ name: 'Post Deploy V1', value: 'postDeployV1', description: 'Deploy collector to managed endpoints', action: 'Post deploy v1' },
			{ name: 'Put Collections V1', value: 'putCollectionsV1', description: 'Update Collections', action: 'Put collections v1' },
			{ name: 'Put Configs V1', value: 'putConfigsV1', description: 'Creates or replaces an existing custom configuration', action: 'Put configs v1' },
			{ name: 'Search Collections V1', value: 'searchCollectionsV1', description: 'Search Collections for given Customer ID/Platform', action: 'Search collections v1' },
			{ name: 'Search Collectors V1', value: 'searchCollectorsV1', description: 'Search Collectors for given Customer ID/Platform', action: 'Search collectors v1' },
			{ name: 'Search Configs V1', value: 'searchConfigsV1', description: 'Search Configurations for the given Customer ID', action: 'Search configs v1' },
			{ name: 'Search Templates V1', value: 'searchTemplatesV1', description: 'Search Templates', action: 'Search templates v1' },
			{ name: 'V1 Host Configs Post', value: 'v1HostConfigsPost', description: 'Configures all hosts in host group to accept execute API call', action: 'V1 host configs post' },
			{ name: 'V1 Status Get', value: 'v1StatusGet', description: 'Fetches host configs within provided host group', action: 'V1 status get' },
			{ name: 'Validate Collection V1', value: 'validateCollectionV1', description: 'Validates a configuration collection', action: 'Validate collection v1' },
			{ name: 'Validate Config V1', value: 'validateConfigV1', description: 'Validates a custom configuration', action: 'Validate config v1' },
		],
		default: 'getCollectionsV1',
	},
];

export const defaultFields: INodeProperties[] = [
	{
		displayName: 'IDs',
		name: 'ids',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['default'],
				operation: [
					'deleteCollectionsV1',
					'deleteConfigsV1',
					'getCollectionsV1',
					'getCollectorsV1',
					'getCombinedCollectionsV1',
					'getCombinedCollectorsV1',
					'getCombinedConfigsV1',
					'getCombinedTemplatesV1',
					'getConfigsV1',
					'getTemplatesV1',
					'v1StatusGet',
				],
			},
		},
		default: '',
		description: 'Comma-separated list of IDs',
	},
	{
		displayName: 'Single ID',
		name: 'idSingle',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['default'],
				operation: ['getConfigDownloadV1'],
			},
		},
		default: '',
		required: true,
		description: 'Configuration ID to download',
	},
	{
		displayName: 'Body (JSON)',
		name: 'bodyJson',
		type: 'json',
		displayOptions: {
			show: {
				resource: ['default'],
				operation: [
					'postCollectionsV1',
					'postCollectorsV1',
					'postConfigsV1',
					'postDeployV1',
					'putCollectionsV1',
					'putConfigsV1',
					'v1HostConfigsPost',
					'validateCollectionV1',
					'validateConfigV1',
				],
			},
		},
		default: '',
		required: true,
		description: 'JSON request payload',
	},
	{
		displayName: 'Filter',
		name: 'filter',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['default'],
				operation: [
					'combinedQueryInstalledPatches',
					'getCollectionCountsByV1',
					'getCombinedCollectionsV1',
					'getCombinedCollectorsV1',
					'getCombinedConfigsV1',
					'getCombinedTemplatesV1',
					'searchCollectionsV1',
					'searchCollectorsV1',
					'searchConfigsV1',
					'searchTemplatesV1',
				],
			},
		},
		default: '',
		description: 'FQL filter string',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
			maxValue: 500,
		},
		displayOptions: {
			show: {
				resource: ['default'],
				operation: [
					'combinedQueryInstalledPatches',
					'getCollectionCountsByV1',
					'getCombinedCollectionsV1',
					'getCombinedCollectorsV1',
					'getCombinedConfigsV1',
					'getCombinedTemplatesV1',
					'searchCollectionsV1',
					'searchCollectorsV1',
					'searchConfigsV1',
					'searchTemplatesV1',
				],
			},
		},
		default: 100,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['default'],
				operation: [
					'getCollectionCountsByV1',
					'getCombinedCollectionsV1',
					'getCombinedCollectorsV1',
					'getCombinedConfigsV1',
					'getCombinedTemplatesV1',
					'searchCollectionsV1',
					'searchCollectorsV1',
					'searchConfigsV1',
					'searchTemplatesV1',
				],
			},
		},
		default: '',
		description: 'Pagination token or offset',
	},
	{
		displayName: 'Sort',
		name: 'sort',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['default'],
				operation: [
					'combinedQueryInstalledPatches',
					'getCollectionCountsByV1',
					'getCollectionsV1',
					'getCollectorsV1',
					'getCombinedCollectionsV1',
					'getCombinedCollectorsV1',
					'getCombinedConfigsV1',
					'getCombinedTemplatesV1',
					'searchCollectionsV1',
					'searchCollectorsV1',
					'searchConfigsV1',
					'searchTemplatesV1',
				],
			},
		},
		default: '',
		description: 'Sort criteria',
	},
];
