import type { INodeProperties } from 'n8n-workflow';

import { createBodyJsonField, createFilterField, createIdsField, createLimitField, createOffsetField, createOperationField, createSortField } from '../common';

export const firewallManagementOperations: INodeProperties[] = [
	createOperationField('firewallManagement', [

			{ name: 'Aggregate Events', value: 'aggregateEvents', description: 'Aggregate events for customer', action: 'Aggregate events' },
			{ name: 'Aggregate Policy Rules', value: 'aggregatePolicyRules', description: 'Aggregate rules within a policy for customer', action: 'Aggregate policy rules' },
			{ name: 'Aggregate Rule Groups', value: 'aggregateRuleGroups', description: 'Aggregate rule groups for customer', action: 'Aggregate rule groups' },
			{ name: 'Aggregate Rules', value: 'aggregateRules', description: 'Aggregate rules for customer', action: 'Aggregate rules' },
			{ name: 'Create Network Locations', value: 'createNetworkLocations', description: 'Create new network locations provided', action: 'Create network locations' },
			{ name: 'Create Rule Group', value: 'createRuleGroup', description: 'Create new rule group on a platform', action: 'Create rule group' },
			{ name: 'Create Rule Group Validation', value: 'createRuleGroupValidation', description: 'Validates request of creating new rule group', action: 'Create rule group validation' },
			{ name: 'Delete Network Locations', value: 'deleteNetworkLocations', description: 'Delete network location entities by ID', action: 'Delete network locations' },
			{ name: 'Delete Rule Groups', value: 'deleteRuleGroups', description: 'Delete rule group entities by ID', action: 'Delete rule groups' },
			{ name: 'Get Events', value: 'getEvents', description: 'Get events entities by ID', action: 'Get events' },
			{ name: 'Get Firewall Fields', value: 'getFirewallFields', description: 'Get firewall field specifications by ID', action: 'Get firewall fields' },
			{ name: 'Get Network Locations', value: 'getNetworkLocations', description: 'Get summary of network locations entities by ID', action: 'Get network locations' },
			{ name: 'Get Network Locations Details', value: 'getNetworkLocationsDetails', description: 'Get complete network locations objects', action: 'Get network locations details' },
			{ name: 'Get Platforms', value: 'getPlatforms', description: 'Get platforms by ID', action: 'Get platforms' },
			{ name: 'Get Policy Containers', value: 'getPolicyContainers', description: 'Get policy container entities by policy ID', action: 'Get policy containers' },
			{ name: 'Get Rule Groups', value: 'getRuleGroups', description: 'Get rule group entities by ID', action: 'Get rule groups' },
			{ name: 'Get Rules', value: 'getRules', description: 'Get rule entities by ID or Family ID', action: 'Get rules' },
			{ name: 'Query Events', value: 'queryEvents', description: 'Find all event IDs matching query with filter', action: 'Query events' },
			{ name: 'Query Firewall Fields', value: 'queryFirewallFields', description: 'Get firewall field specification IDs for platform', action: 'Query firewall fields' },
			{ name: 'Query Network Locations', value: 'queryNetworkLocations', description: 'Get list of network location IDs', action: 'Query network locations' },
			{ name: 'Query Platforms', value: 'queryPlatforms', description: 'Get list of platform names', action: 'Query platforms' },
			{ name: 'Query Policy Rules', value: 'queryPolicyRules', description: 'Find firewall rule IDs matching query in precedence order', action: 'Query policy rules' },
			{ name: 'Query Rule Groups', value: 'queryRuleGroups', description: 'Find all rule group IDs matching query', action: 'Query rule groups' },
			{ name: 'Query Rules', value: 'queryRules', description: 'Find all rule IDs matching query', action: 'Query rules' },
			{ name: 'Update Network Locations', value: 'updateNetworkLocations', description: 'Updates network locations provided', action: 'Update network locations' },
			{ name: 'Update Network Locations Metadata', value: 'updateNetworkLocationsMetadata', description: 'Updates network locations metadata', action: 'Update network locations metadata' },
			{ name: 'Update Network Locations Precedence', value: 'updateNetworkLocationsPrecedence', description: 'Updates network locations precedence', action: 'Update network locations precedence' },
			{ name: 'Update Policy Container', value: 'updatePolicyContainer', description: 'Update identified policy container including local logging', action: 'Update policy container' },
			{ name: 'Update Policy Container V1 (Deprecated)', value: 'updatePolicyContainerV1', description: 'Update identified policy container (deprecated)', action: 'Update policy container v1' },
			{ name: 'Update Rule Group', value: 'updateRuleGroup', description: 'Update name, description, or enabled status of rule group', action: 'Update rule group' },
			{ name: 'Update Rule Group Validation', value: 'updateRuleGroupValidation', description: 'Validates request of updating rule group', action: 'Update rule group validation' },
			{ name: 'Upsert Network Locations', value: 'upsertNetworkLocations', description: 'Updates network locations provided', action: 'Upsert network locations' },
			{ name: 'Validate Filepath Pattern', value: 'validateFilepathPattern', description: 'Validates test pattern matches executable filepath glob', action: 'Validate filepath pattern' },
		
	], 'queryRules'),
];

export const firewallManagementFields: INodeProperties[] = [
	{
		displayName: 'Policy Container ID / Policy Rule ID',
		name: 'id',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['firewallManagement'],
				operation: ['queryPolicyRules'],
			},
		},
		default: '',
		description: 'Target policy or container ID',
	},
	createIdsField('firewallManagement', ['deleteNetworkLocations',
					'deleteRuleGroups',
					'getEvents',
					'getFirewallFields',
					'getNetworkLocations',
					'getNetworkLocationsDetails',
					'getPlatforms',
					'getPolicyContainers',
					'getRuleGroups',
					'getRules',]),
	{
		displayName: 'Platform ID',
		name: 'platformId',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['firewallManagement'],
				operation: ['queryFirewallFields'],
			},
		},
		default: '',
		description: 'Platform ID string',
	},
	{
		displayName: 'Comment',
		name: 'comment',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['firewallManagement'],
				operation: [
					'createNetworkLocations',
					'createRuleGroup',
					'createRuleGroupValidation',
					'deleteRuleGroups',
					'updateNetworkLocations',
					'updateNetworkLocationsMetadata',
					'updateNetworkLocationsPrecedence',
					'updateRuleGroup',
					'updateRuleGroupValidation',
					'upsertNetworkLocations',
				],
			},
		},
		default: '',
		description: 'Audit log comment string',
	},
	createBodyJsonField('firewallManagement', ['aggregateEvents',
					'aggregatePolicyRules',
					'aggregateRuleGroups',
					'aggregateRules',
					'createNetworkLocations',
					'createRuleGroup',
					'createRuleGroupValidation',
					'updateNetworkLocations',
					'updateNetworkLocationsMetadata',
					'updateNetworkLocationsPrecedence',
					'updatePolicyContainer',
					'updatePolicyContainerV1',
					'updateRuleGroup',
					'updateRuleGroupValidation',
					'upsertNetworkLocations',
					'validateFilepathPattern',]),
	createFilterField('firewallManagement', ['queryEvents',
					'queryNetworkLocations',
					'queryPolicyRules',
					'queryRuleGroups',
					'queryRules',]),
	{
		displayName: 'Search Query (q)',
		name: 'q',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['firewallManagement'],
				operation: [
					'queryEvents',
					'queryNetworkLocations',
					'queryPolicyRules',
					'queryRuleGroups',
					'queryRules',
				],
			},
		},
		default: '',
		description: 'Search string',
	},
	createLimitField('firewallManagement', ['queryEvents',
					'queryFirewallFields',
					'queryNetworkLocations',
					'queryPlatforms',
					'queryPolicyRules',
					'queryRuleGroups',
					'queryRules',]),
	createOffsetField('firewallManagement', ['queryEvents',
					'queryFirewallFields',
					'queryNetworkLocations',
					'queryPlatforms',
					'queryPolicyRules',
					'queryRuleGroups',
					'queryRules',]),
	createSortField('firewallManagement', ['queryEvents',
					'queryNetworkLocations',
					'queryPolicyRules',
					'queryRuleGroups',
					'queryRules',]),
];
