import type { INodeProperties } from 'n8n-workflow';

export const ngsiemOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['ngsiem'],
			},
		},
		options: [
			{ name: 'Bulk Create Dashboards from Template', value: 'bulkCreateDashboardsFromTemplate', description: 'Create Multiple Dashboards from YAML Templates', action: 'Bulk create dashboards from template' },
			{ name: 'Bulk Create Lookup Files', value: 'bulkCreateLookupFiles', description: 'Create Multiple Lookup Files', action: 'Bulk create lookup files' },
			{ name: 'Bulk Create Saved Queries from Template', value: 'bulkCreateSavedQueriesFromTemplate', description: 'Create Multiple Saved Queries from LogScale YAML Templates', action: 'Bulk create saved queries from template' },
			{ name: 'Bulk Get Lookup Files', value: 'bulkGetLookupFiles', description: 'Retrieve Multiple Lookup Files by Filenames in NGSIEM', action: 'Bulk get lookup files' },
			{ name: 'Bulk Install Parsers', value: 'bulkInstallParsers', description: 'Installs multiple CrowdStrike-managed OOTB parsers', action: 'Bulk install parsers' },
			{ name: 'Bulk Update Dashboards from Template', value: 'bulkUpdateDashboardsFromTemplate', description: 'Update Multiple Dashboards from YAML Templates', action: 'Bulk update dashboards from template' },
			{ name: 'Bulk Update Lookup Files', value: 'bulkUpdateLookupFiles', description: 'Update Multiple Lookup Files', action: 'Bulk update lookup files' },
			{ name: 'Bulk Update Saved Queries from Template', value: 'bulkUpdateSavedQueriesFromTemplate', description: 'Update Multiple Saved Queries from LogScale YAML Templates', action: 'Bulk update saved queries from template' },
			{ name: 'Clone Parser', value: 'cloneParser', description: 'Clone an existing parser with a new name', action: 'Clone parser' },
			{ name: 'Create Dashboard from Template', value: 'createDashboardFromTemplate', description: 'Create Dashboard from LogScale YAML Template in NGSIEM', action: 'Create dashboard from template' },
			{ name: 'Create Lookup File', value: 'createLookupFile', description: 'Create Lookup File in NGSIEM', action: 'Create lookup file' },
			{ name: 'Create Parser', value: 'createParser', description: 'Create Parser in NGSIEM (Deprecated)', action: 'Create parser' },
			{ name: 'Create Parser Extension', value: 'createParserExtension', description: 'Create a Parser extension in NGSIEM for provided base parser', action: 'Create parser extension' },
			{ name: 'Create Parser from Template', value: 'createParserFromTemplate', description: 'Create Parser from LogScale YAML Template in NGSIEM', action: 'Create parser from template' },
			{ name: 'Create Saved Query', value: 'createSavedQuery', description: 'Create Saved Query from LogScale YAML Template in NGSIEM', action: 'Create saved query' },
			{ name: 'Delete Dashboard', value: 'deleteDashboard', description: 'Delete Dashboard in NGSIEM', action: 'Delete dashboard' },
			{ name: 'Delete Lookup File', value: 'deleteLookupFile', description: 'Delete Lookup File in NGSIEM', action: 'Delete lookup file' },
			{ name: 'Delete Parser', value: 'deleteParser', description: 'Delete Parser in NGSIEM', action: 'Delete parser' },
			{ name: 'Delete Saved Query', value: 'deleteSavedQuery', description: 'Delete Saved Query in NGSIEM', action: 'Delete saved query' },
			{ name: 'External Create Connector Config', value: 'externalCreateConnectorConfig', description: 'Create a new configuration for a data connector', action: 'External create connector config' },
			{ name: 'External Create Data Connection', value: 'externalCreateDataConnection', description: 'Create a new data connection', action: 'External create data connection' },
			{ name: 'External Delete Connector Configs', value: 'externalDeleteConnectorConfigs', description: 'Delete data connection config', action: 'External delete connector configs' },
			{ name: 'External Delete Data Connection', value: 'externalDeleteDataConnection', description: 'Delete a data connection', action: 'External delete data connection' },
			{ name: 'External Get Data Connection by ID', value: 'externalGetDataConnectionByID', description: 'Get data connection by ID', action: 'External get data connection by ID' },
			{ name: 'External Get Data Connection Status', value: 'externalGetDataConnectionStatus', description: 'Get data connection provisioning status', action: 'External get data connection status' },
			{ name: 'External Get Data Connection Token', value: 'externalGetDataConnectionToken', description: 'Get Ingest token for data connection', action: 'External get data connection token' },
			{ name: 'External List Connector Configs', value: 'externalListConnectorConfigs', description: 'List configurations for a data connector', action: 'External list connector configs' },
			{ name: 'External List Data Connections', value: 'externalListDataConnections', description: 'List and search data connections', action: 'External list data connections' },
			{ name: 'External List Data Connectors', value: 'externalListDataConnectors', description: 'List available data connectors', action: 'External list data connectors' },
			{ name: 'External Patch Connector Config', value: 'externalPatchConnectorConfig', description: 'Patch configurations for a data connector', action: 'External patch connector config' },
			{ name: 'External Regenerate Data Connection Token', value: 'externalRegenerateDataConnectionToken', description: 'Regenerate Ingest token for data connection', action: 'External regenerate data connection token' },
			{ name: 'External Update Data Connection', value: 'externalUpdateDataConnection', description: 'Update a data connection', action: 'External update data connection' },
			{ name: 'External Update Data Connection Status', value: 'externalUpdateDataConnectionStatus', description: 'Update data connection status', action: 'External update data connection status' },
			{ name: 'Get Dashboard Template', value: 'getDashboardTemplate', description: 'Retrieve Dashboard(s) in NGSIEM as LogScale YAML Template', action: 'Get dashboard template' },
			{ name: 'Get Lookup File', value: 'getLookupFile', description: 'Retrieve Lookup File in NGSIEM', action: 'Get lookup file' },
			{ name: 'Get Lookup from Package V1', value: 'getLookupFromPackageV1', description: 'Download lookup file in package from NGSIEM', action: 'Get lookup from package V1' },
			{ name: 'Get Lookup from Package with Namespace V1', value: 'getLookupFromPackageWithNamespaceV1', description: 'Download lookup file in namespaced package from NGSIEM', action: 'Get lookup from package with namespace V1' },
			{ name: 'Get Lookup V1', value: 'getLookupV1', description: 'Download lookup file from NGSIEM', action: 'Get lookup V1' },
			{ name: 'Get Parser', value: 'getParser', description: 'Retrieve Parser in NGSIEM (Deprecated)', action: 'Get parser' },
			{ name: 'Get Parser Template', value: 'getParserTemplate', description: 'Retrieve Parser in NGSIEM as LogScale YAML Template', action: 'Get parser template' },
			{ name: 'Get Saved Query Template', value: 'getSavedQueryTemplate', description: 'Retrieve Saved Quer(ies) in NGSIEM as LogScale YAML Template', action: 'Get saved query template' },
			{ name: 'Get Search Status V1', value: 'getSearchStatusV1', description: 'Get status of search', action: 'Get search status V1' },
			{ name: 'Install Parser', value: 'installParser', description: 'Installs a CrowdStrike-managed OOTB parser', action: 'Install parser' },
			{ name: 'List Dashboards', value: 'listDashboards', description: 'List Dashboards in NGSIEM with Pagination and Filtering', action: 'List dashboards' },
			{ name: 'List Lookup Files', value: 'listLookupFiles', description: 'List Lookup Files in NGSIEM with Pagination and Filtering', action: 'List lookup files' },
			{ name: 'List Parsers', value: 'listParsers', description: 'List Parsers in NGSIEM', action: 'List parsers' },
			{ name: 'List Saved Queries', value: 'listSavedQueries', description: 'List Saved Queries in NGSIEM with Pagination and Filtering', action: 'List saved queries' },
			{ name: 'Start Search V1', value: 'startSearchV1', description: 'Initiate search', action: 'Start search V1' },
			{ name: 'Stop Search V1', value: 'stopSearchV1', description: 'Stop search', action: 'Stop search V1' },
			{ name: 'Test Parser from Template', value: 'testParserFromTemplate', description: 'Test Parser from LogScale YAML Template in NGSIEM', action: 'Test parser from template' },
			{ name: 'Update Dashboard from Template', value: 'updateDashboardFromTemplate', description: 'Update Dashboard from LogScale YAML Template in NGSIEM', action: 'Update dashboard from template' },
			{ name: 'Update Lookup File', value: 'updateLookupFile', description: 'Update an entire Lookup File in NGSIEM', action: 'Update lookup file' },
			{ name: 'Update Lookup File Entries', value: 'updateLookupFileEntries', description: 'Update entries in an existing Lookup File in NGSIEM', action: 'Update lookup file entries' },
			{ name: 'Update Parser', value: 'updateParser', description: 'Update Parser in NGSIEM (Deprecated)', action: 'Update parser' },
			{ name: 'Update Parser Auto Update Policy', value: 'updateParserAutoUpdatePolicy', description: 'Updates a parser auto update policy', action: 'Update parser auto update policy' },
			{ name: 'Update Parser Extension', value: 'updateParserExtension', description: 'Update an existing Parser extension in NGSIEM', action: 'Update parser extension' },
			{ name: 'Update Parser from Template', value: 'updateParserFromTemplate', description: 'Update Parser in NGSIEM from YAML Template', action: 'Update parser from template' },
			{ name: 'Update Saved Query from Template', value: 'updateSavedQueryFromTemplate', description: 'Update Saved Query from LogScale YAML Template in NGSIEM', action: 'Update saved query from template' },
			{ name: 'Upload Lookup V1', value: 'uploadLookupV1', description: 'Upload file to NGSIEM', action: 'Upload lookup V1' },
		],
		default: 'listDashboards',
	},
];

export const ngsiemFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'externalDeleteDataConnection',
					'externalGetDataConnectionToken',
					'externalListConnectorConfigs',
					'externalPatchConnectorConfig',
					'externalRegenerateDataConnectionToken',
					'externalUpdateDataConnection',
					'externalUpdateDataConnectionStatus',
					'getSearchStatusV1',
					'stopSearchV1',
				],
			},
		},
		default: '',
		description: 'Unique ID string',
	},
	{
		displayName: 'IDs',
		name: 'ids',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'deleteDashboard',
					'deleteParser',
					'deleteSavedQuery',
					'externalDeleteConnectorConfigs',
					'externalGetDataConnectionByID',
					'externalGetDataConnectionStatus',
					'getDashboardTemplate',
					'getParser',
					'getParserTemplate',
					'getSavedQueryTemplate',
					'updateDashboardFromTemplate',
					'updateParserFromTemplate',
					'updateSavedQueryFromTemplate',
				],
			},
		},
		default: '',
		description: 'Comma-separated list of IDs',
	},
	{
		displayName: 'Repository',
		name: 'repository',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'getLookupFromPackageV1',
					'getLookupFromPackageWithNamespaceV1',
					'getLookupV1',
					'getSearchStatusV1',
					'startSearchV1',
					'stopSearchV1',
					'uploadLookupV1',
				],
			},
		},
		default: '',
		description: 'Target Repository name',
	},
	{
		displayName: 'Filename',
		name: 'filename',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'bulkGetLookupFiles',
					'deleteLookupFile',
					'getLookupFile',
					'getLookupFromPackageV1',
					'getLookupFromPackageWithNamespaceV1',
					'getLookupV1',
				],
			},
		},
		default: '',
		description: 'Filename string or comma-separated list of filenames',
	},
	{
		displayName: 'Body (JSON)',
		name: 'bodyJson',
		type: 'json',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'bulkCreateDashboardsFromTemplate',
					'bulkCreateLookupFiles',
					'bulkCreateSavedQueriesFromTemplate',
					'bulkInstallParsers',
					'bulkUpdateDashboardsFromTemplate',
					'bulkUpdateLookupFiles',
					'bulkUpdateSavedQueriesFromTemplate',
					'cloneParser',
					'createParser',
					'createParserExtension',
					'externalCreateConnectorConfig',
					'externalCreateDataConnection',
					'installParser',
					'startSearchV1',
					'updateParser',
					'updateParserAutoUpdatePolicy',
					'updateParserExtension',
				],
			},
		},
		default: '',
		required: true,
		description: 'JSON request payload',
	},
	{
		displayName: 'Filter',
		name: 'filter',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'externalListDataConnections',
					'externalListDataConnectors',
					'listDashboards',
					'listLookupFiles',
					'listParsers',
					'listSavedQueries',
				],
			},
		},
		default: '',
		description: 'Filter string',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
			maxValue: 500,
		},
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'externalListDataConnections',
					'externalListDataConnectors',
					'listDashboards',
					'listLookupFiles',
					'listParsers',
					'listSavedQueries',
				],
			},
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: {
			minValue: 0,
		},
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: [
					'externalListDataConnections',
					'externalListDataConnectors',
					'listDashboards',
					'listLookupFiles',
					'listParsers',
					'listSavedQueries',
				],
			},
		},
		default: 0,
		description: 'Starting index for pagination',
	},
	{
		displayName: 'Sort',
		name: 'sort',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['ngsiem'],
				operation: ['externalListDataConnections', 'externalListDataConnectors'],
			},
		},
		default: '',
		description: 'Sort criteria',
	},
];
