import type { INodeProperties } from 'n8n-workflow';

export const dataProtectionConfigurationOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
			},
		},
		options: [
			{ name: 'Entities Classification Delete V2', value: 'entitiesClassificationDeleteV2', description: 'Deletes classifications matching IDs', action: 'Entities classification delete V2' },
			{ name: 'Entities Classification Get V2', value: 'entitiesClassificationGetV2', description: 'Gets classifications matching IDs', action: 'Entities classification get V2' },
			{ name: 'Entities Classification Patch V2', value: 'entitiesClassificationPatchV2', description: 'Update classifications', action: 'Entities classification patch V2' },
			{ name: 'Entities Classification Post V2', value: 'entitiesClassificationPostV2', description: 'Create classifications', action: 'Entities classification post V2' },
			{ name: 'Entities Cloud Application Create', value: 'entitiesCloudApplicationCreate', description: 'Create cloud application', action: 'Entities cloud application create' },
			{ name: 'Entities Cloud Application Delete', value: 'entitiesCloudApplicationDelete', description: 'Delete cloud application', action: 'Entities cloud application delete' },
			{ name: 'Entities Cloud Application Get', value: 'entitiesCloudApplicationGet', description: 'Get cloud application by IDs', action: 'Entities cloud application get' },
			{ name: 'Entities Cloud Application Patch', value: 'entitiesCloudApplicationPatch', description: 'Update cloud application', action: 'Entities cloud application patch' },
			{ name: 'Entities Content Pattern Create', value: 'entitiesContentPatternCreate', description: 'Create content pattern', action: 'Entities content pattern create' },
			{ name: 'Entities Content Pattern Delete', value: 'entitiesContentPatternDelete', description: 'Delete content pattern', action: 'Entities content pattern delete' },
			{ name: 'Entities Content Pattern Get', value: 'entitiesContentPatternGet', description: 'Get content pattern by IDs', action: 'Entities content pattern get' },
			{ name: 'Entities Content Pattern Patch', value: 'entitiesContentPatternPatch', description: 'Update content pattern', action: 'Entities content pattern patch' },
			{ name: 'Entities Enterprise Account Create', value: 'entitiesEnterpriseAccountCreate', description: 'Create enterprise account', action: 'Entities enterprise account create' },
			{ name: 'Entities Enterprise Account Delete', value: 'entitiesEnterpriseAccountDelete', description: 'Delete enterprise account', action: 'Entities enterprise account delete' },
			{ name: 'Entities Enterprise Account Get', value: 'entitiesEnterpriseAccountGet', description: 'Get enterprise account by IDs', action: 'Entities enterprise account get' },
			{ name: 'Entities Enterprise Account Patch', value: 'entitiesEnterpriseAccountPatch', description: 'Update enterprise account', action: 'Entities enterprise account patch' },
			{ name: 'Entities File Type Get', value: 'entitiesFileTypeGet', description: 'Get file type by IDs', action: 'Entities file type get' },
			{ name: 'Entities Local Application Create', value: 'entitiesLocalApplicationCreate', description: 'Create local application', action: 'Entities local application create' },
			{ name: 'Entities Local Application Delete', value: 'entitiesLocalApplicationDelete', description: 'Soft delete local application', action: 'Entities local application delete' },
			{ name: 'Entities Local Application Get', value: 'entitiesLocalApplicationGet', description: 'Get local application by IDs', action: 'Entities local application get' },
			{ name: 'Entities Local Application Group Create', value: 'entitiesLocalApplicationGroupCreate', description: 'Create local application group', action: 'Entities local application group create' },
			{ name: 'Entities Local Application Group Delete', value: 'entitiesLocalApplicationGroupDelete', description: 'Soft delete local application group', action: 'Entities local application group delete' },
			{ name: 'Entities Local Application Group Get', value: 'entitiesLocalApplicationGroupGet', description: 'Get local application group by IDs', action: 'Entities local application group get' },
			{ name: 'Entities Local Application Group Patch', value: 'entitiesLocalApplicationGroupPatch', description: 'Update local application group', action: 'Entities local application group patch' },
			{ name: 'Entities Local Application Patch', value: 'entitiesLocalApplicationPatch', description: 'Update local application', action: 'Entities local application patch' },
			{ name: 'Entities Policy Delete V2', value: 'entitiesPolicyDeleteV2', description: 'Deletes policies matching IDs', action: 'Entities policy delete V2' },
			{ name: 'Entities Policy Get V2', value: 'entitiesPolicyGetV2', description: 'Gets policies matching IDs', action: 'Entities policy get V2' },
			{ name: 'Entities Policy Patch V2', value: 'entitiesPolicyPatchV2', description: 'Update policies', action: 'Entities policy patch V2' },
			{ name: 'Entities Policy Post V2', value: 'entitiesPolicyPostV2', description: 'Create policies', action: 'Entities policy post V2' },
			{ name: 'Entities Policy Precedence Post V1', value: 'entitiesPolicyPrecedencePostV1', description: 'Update policy precedence', action: 'Entities policy precedence post V1' },
			{ name: 'Entities Sensitivity Label Create V2', value: 'entitiesSensitivityLabelCreateV2', description: 'Create sensitivity label V2', action: 'Entities sensitivity label create V2' },
			{ name: 'Entities Sensitivity Label Delete V2', value: 'entitiesSensitivityLabelDeleteV2', description: 'Delete sensitivity labels V2', action: 'Entities sensitivity label delete V2' },
			{ name: 'Entities Sensitivity Label Get V2', value: 'entitiesSensitivityLabelGetV2', description: 'Get sensitivity labels V2', action: 'Entities sensitivity label get V2' },
			{ name: 'Entities Web Location Create V2', value: 'entitiesWebLocationCreateV2', description: 'Create web location V2', action: 'Entities web location create V2' },
			{ name: 'Entities Web Location Delete V2', value: 'entitiesWebLocationDeleteV2', description: 'Delete web location V2', action: 'Entities web location delete V2' },
			{ name: 'Entities Web Location Get V2', value: 'entitiesWebLocationGetV2', description: 'Get web location V2', action: 'Entities web location get V2' },
			{ name: 'Entities Web Location Patch V2', value: 'entitiesWebLocationPatchV2', description: 'Update web location V2', action: 'Entities web location patch V2' },
			{ name: 'Queries Classification Get V2', value: 'queriesClassificationGetV2', description: 'Search classifications matching criteria', action: 'Queries classification get V2' },
			{ name: 'Queries Cloud Application Get V2', value: 'queriesCloudApplicationGetV2', description: 'Get cloud application IDs with filter', action: 'Queries cloud application get V2' },
			{ name: 'Queries Content Pattern Get V2', value: 'queriesContentPatternGetV2', description: 'Get content pattern IDs with filter', action: 'Queries content pattern get V2' },
			{ name: 'Queries Enterprise Account Get V2', value: 'queriesEnterpriseAccountGetV2', description: 'Get enterprise account IDs with filter', action: 'Queries enterprise account get V2' },
			{ name: 'Queries File Type Get V2', value: 'queriesFileTypeGetV2', description: 'Get file type IDs with filter', action: 'Queries file type get V2' },
			{ name: 'Queries Local Application Get', value: 'queriesLocalApplicationGet', description: 'Get local application IDs with filter', action: 'Queries local application get' },
			{ name: 'Queries Local Application Group Get', value: 'queriesLocalApplicationGroupGet', description: 'Get local application group IDs with filter', action: 'Queries local application group get' },
			{ name: 'Queries Policy Get V2', value: 'queriesPolicyGetV2', description: 'Search policies matching criteria', action: 'Queries policy get V2' },
			{ name: 'Queries Sensitivity Label Get V2', value: 'queriesSensitivityLabelGetV2', description: 'Get sensitivity label IDs with filter', action: 'Queries sensitivity label get V2' },
			{ name: 'Queries Web Location Get V2', value: 'queriesWebLocationGetV2', description: 'Get web location IDs with filter', action: 'Queries web location get V2' },
		],
		default: 'queriesPolicyGetV2',
	},
];

export const dataProtectionConfigurationFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'entitiesCloudApplicationPatch',
					'entitiesContentPatternPatch',
					'entitiesEnterpriseAccountPatch',
					'entitiesLocalApplicationGroupPatch',
					'entitiesLocalApplicationPatch',
					'entitiesWebLocationPatchV2',
				],
			},
		},
		default: '',
		required: true,
		description: 'Target ID',
	},
	{
		displayName: 'IDs',
		name: 'ids',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'entitiesClassificationDeleteV2',
					'entitiesClassificationGetV2',
					'entitiesCloudApplicationDelete',
					'entitiesCloudApplicationGet',
					'entitiesContentPatternDelete',
					'entitiesContentPatternGet',
					'entitiesEnterpriseAccountDelete',
					'entitiesEnterpriseAccountGet',
					'entitiesFileTypeGet',
					'entitiesLocalApplicationDelete',
					'entitiesLocalApplicationGet',
					'entitiesLocalApplicationGroupDelete',
					'entitiesLocalApplicationGroupGet',
					'entitiesPolicyDeleteV2',
					'entitiesPolicyGetV2',
					'entitiesSensitivityLabelDeleteV2',
					'entitiesSensitivityLabelGetV2',
					'entitiesWebLocationDeleteV2',
					'entitiesWebLocationGetV2',
				],
			},
		},
		default: '',
		required: true,
		description: 'Comma-separated list of IDs',
	},
	{
		displayName: 'Platform Name',
		name: 'platformName',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'entitiesPolicyDeleteV2',
					'entitiesPolicyPatchV2',
					'entitiesPolicyPostV2',
					'queriesPolicyGetV2',
				],
			},
		},
		default: 'Windows',
		required: true,
		description: 'Platform name (e.g. Windows, Mac, Linux)',
	},
	{
		displayName: 'User UUID',
		name: 'xCSUSERUUID',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: ['queriesLocalApplicationGet', 'queriesLocalApplicationGroupGet'],
			},
		},
		default: '',
		required: true,
		description: 'User UUID string',
	},
	{
		displayName: 'Body (JSON)',
		name: 'bodyJson',
		type: 'json',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'entitiesClassificationPatchV2',
					'entitiesClassificationPostV2',
					'entitiesCloudApplicationCreate',
					'entitiesCloudApplicationPatch',
					'entitiesContentPatternCreate',
					'entitiesContentPatternPatch',
					'entitiesEnterpriseAccountCreate',
					'entitiesEnterpriseAccountPatch',
					'entitiesLocalApplicationCreate',
					'entitiesLocalApplicationGroupCreate',
					'entitiesLocalApplicationGroupPatch',
					'entitiesLocalApplicationPatch',
					'entitiesPolicyPatchV2',
					'entitiesPolicyPostV2',
					'entitiesPolicyPrecedencePostV1',
					'entitiesSensitivityLabelCreateV2',
					'entitiesWebLocationCreateV2',
					'entitiesWebLocationPatchV2',
				],
			},
		},
		default: '',
		required: true,
		description: 'JSON request payload',
	},
	{
		displayName: 'Filter',
		name: 'filter',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'queriesClassificationGetV2',
					'queriesCloudApplicationGetV2',
					'queriesContentPatternGetV2',
					'queriesEnterpriseAccountGetV2',
					'queriesFileTypeGetV2',
					'queriesLocalApplicationGet',
					'queriesLocalApplicationGroupGet',
					'queriesPolicyGetV2',
					'queriesSensitivityLabelGetV2',
					'queriesWebLocationGetV2',
				],
			},
		},
		default: '',
		description: 'FQL filter string',
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: ['queriesWebLocationGetV2'],
			},
		},
		default: '',
		description: 'Location type filter',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
			maxValue: 500,
		},
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'queriesClassificationGetV2',
					'queriesCloudApplicationGetV2',
					'queriesContentPatternGetV2',
					'queriesEnterpriseAccountGetV2',
					'queriesFileTypeGetV2',
					'queriesLocalApplicationGet',
					'queriesLocalApplicationGroupGet',
					'queriesPolicyGetV2',
					'queriesSensitivityLabelGetV2',
					'queriesWebLocationGetV2',
				],
			},
		},
		default: 100,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: {
			minValue: 0,
		},
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'queriesClassificationGetV2',
					'queriesCloudApplicationGetV2',
					'queriesContentPatternGetV2',
					'queriesEnterpriseAccountGetV2',
					'queriesFileTypeGetV2',
					'queriesLocalApplicationGet',
					'queriesLocalApplicationGroupGet',
					'queriesPolicyGetV2',
					'queriesSensitivityLabelGetV2',
					'queriesWebLocationGetV2',
				],
			},
		},
		default: 0,
		description: 'Starting index for pagination',
	},
	{
		displayName: 'Sort',
		name: 'sort',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['dataProtectionConfiguration'],
				operation: [
					'queriesClassificationGetV2',
					'queriesCloudApplicationGetV2',
					'queriesContentPatternGetV2',
					'queriesEnterpriseAccountGetV2',
					'queriesFileTypeGetV2',
					'queriesPolicyGetV2',
					'queriesSensitivityLabelGetV2',
				],
			},
		},
		default: '',
		description: 'Sort criteria',
	},
];
